name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set environment variables for image tagging
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          BRANCH_NAME=${GITHUB_REF/refs\/heads\//}
          echo "BRANCH_NAME=`echo ${BRANCH_NAME/\//-}`" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            harvardat/rstudio-${{ env.BRANCH_NAME }}:${{ env.SHORT_SHA }}
            harvardat/rstudio-${{ env.BRANCH_NAME }}:latest
